package aoc

import kotlin.test.Test
import kotlin.test.assertEquals

class Day08Test {
    private val sampleInput = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """.trimIndent().lines()

    private val minimalInput = """
        a....a......
        ............
        ............
    """.trimIndent().lines()

    private val singleFrequencyLine = """
        ............
        ..A.........
        ....A.......
        ......A.....
        ............
    """.trimIndent().lines()

    private val edgeInput = """
        A...........
        ...........A
        ............
        ............
        ........A...
    """.trimIndent().lines()

    @Test
    fun testPart1() {
        val day08 = Day08()

        assertEquals(14, day08.part1(sampleInput), "Sample input for Part 1 failed")
        assertEquals(1, day08.part1(minimalInput), "Minimal input for Part 1 failed")
        assertEquals(4, day08.part1(singleFrequencyLine), "Single frequency line for Part 1 failed")
        assertEquals(2, day08.part1(edgeInput), "Edge input for Part 1 failed")
    }

    @Test
    fun testPart2() {
        val day08 = Day08()

        assertEquals(34, day08.part2(sampleInput), "Sample input for Part 2 failed")
        assertEquals(3, day08.part2(minimalInput), "Minimal input for Part 2 failed")
        assertEquals(12, day08.part2(singleFrequencyLine), "Single frequency line for Part 2 failed")
        assertEquals(5, day08.part2(edgeInput), "Edge input for Part 2 failed")
    }
}
